### PR TITLE
Add syntax for .git files

### PR DESCRIPTION
**Pull request by deathaxe**
Git uses .git files to link a work-tree of a submodule to the main repositories database.

It most likely contains a line like:

   gitdir: ../../path/.git.

This commit adds a syntax file to highlight the keyword and the path.

### CODE REVIEW

**Comment by y0ssar1an** [comment]
Are these `.git` link files a Windows thing? I've never seen one before. This is still great, though! Let's get this merged 😃

**Comment by deathaxe** [comment]
I don't think its windows specific. Git creates such files within each submodule you add to a repository, or if you checkout custom/multiple work-trees. They just might be hidden on Linux/OSX by default?

**Comment by deathaxe** [comment]
Ready to merge.

**Comment by y0ssar1an** [comment]
I merged #1 and #2. Can you please rebase this? I don't want to accidentally revert your hard work.

**Comment by deathaxe** [comment]
This PR should merge without conflicts as it contains new files only.

**Comment by y0ssar1an** [comment]
I'm confused. [The GitHub diff](https://github.com/y0ssar1an/Packages/pull/3/files) shows old filenames and old versions of `commit.sublime-syntax`.

**Comment by deathaxe** [comment]
Ah, see - you are right - good catch. I merged it locally without issues. Therefore I missed GitHub didn't update the base-branch, which moved forward in the meanwhile. I rebased the PR onto the HEAD of add_gitconfig_pkg. Now it's save to merge.

**Pull request merged**
