### PR TITLE
Improve git commit messages

### PR DESCRIPTION
**Pull request by deathaxe**
For details please refer to the commit messages.

### CODE REVIEW

**Comment by y0ssar1an** [comment]
You've done a lot of work here 👏 . Let's replace my `commit.sublime-syntax` wholesale with this. I'm gonna push the last changes I made. Then we have to reconcile the filename and scope name changes.

**Comment by deathaxe** [comment]
Yep. Maybe most efficient to do that in one branch later.

**Comment by y0ssar1an** [comment]
I'm gonna step away from the keyboard to give you a chance to get these merged. Sorry again for the force pushes.

**Comment by deathaxe** [comment]
I merged my branch into yours locally and pushed the result. If you pull the results you should be able to merge with a fast-forward.

**Pull request merged**
